classic_queue.default_version = 2
loopback_users = none

log.console = true
log.console.level = debug
log.file.level = info
log.exchange = false
log.exchange.level = info

auth_backends.1 = internal
auth_backends.2.authn = ldap
auth_backends.2.authz = internal

auth_ldap.servers.1 = ldap.ad.example.com
auth_ldap.use_ssl = true
auth_ldap.port = 636
auth_ldap.dn_lookup_bind.user_dn = CN=mqadmin-lab,OU=ServiceAccounts,OU=LAB,OU=RabbitMQ,OU=Services,OU=ExampleOrg,DC=ad,DC=example,DC=com
auth_ldap.dn_lookup_bind.password = RedactedPassword
auth_ldap.dn_lookup_attribute = sAMAccountName
auth_ldap.dn_lookup_base = DC=ad,DC=example,DC=com
auth_ldap.log = network_unsafe
